services:
  # 1. Layanan Frontend (React + Nginx)
  frontend:
    build:
      context: . # Menggunakan Dockerfile di root direktori
      dockerfile: Dockerfile
      args:
        - VITE_API_URL="https://warp-server.up.railway.app"
    container_name: lapor_frontend
    ports:
      - "80:80" # Memetakan port 80 VPS ke port 80 container
    restart: unless-stopped

  # 2. Layanan Backend Utama (Node.js)
  server:
    build: ./server # Membangun dari Dockerfile di dalam folder 'server'
    container_name: lapor_backend
    env_file:
      - ./server/.env # Memuat environment variables dari file .env
    ports:
      - "8000:8000" # Ganti port sesuai dengan port aplikasi Node.js Anda
    restart: unless-stopped
    depends_on:
      - yolo_server # Memastikan server AI jalan duluan jika perlu

  # 3. Layanan AI (Python YOLO)
  yolo_server:
    build: ./yolo_server # Membangun dari Dockerfile di dalam folder 'yolo_server'
    container_name: lapor_yolo_server
    env_file:
      - ./yolo_server/.env # Memuat environment variables dari file .env
    ports:
      - "5000:5000" # Ganti port sesuai dengan port aplikasi Python Anda
    restart: unless-stopped