version: '3.8' # Menentukan versi Docker Compose

# Mendefinisikan semua layanan/server yang akan kita jalankan
services:
  # Layanan untuk backend utama Node.js
  backend_utama:
    # Memberitahu Docker untuk membangun image dari Dockerfile di folder ./server
    build: ./server
    # Menghubungkan port 8000 di dalam kontainer ke port 8000 di komputer Anda
    # agar kita bisa mengaksesnya dari luar.
    ports:
      - "8000:8000"
    # Meneruskan API Key dari file .env di folder root ke dalam kontainer ini
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    # Memberitahu bahwa layanan ini bergantung pada server_yolo.
    # Docker akan memastikan server_yolo jalan terlebih dahulu.
    depends_on:
      - server_yolo

  # Layanan untuk backend AI Python
  server_yolo:
    # Membangun image dari Dockerfile di folder ./yolo_server
    build: ./yolo_server
    # Kita tidak perlu 'ports' di sini karena hanya akan diakses
    # oleh 'backend_utama' secara internal di dalam jaringan Docker.