services:
  # 1) Frontend (Nginx menyajikan build React & proxy /api ke backend)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      # kamu TIDAK wajib passing VITE_API_URL kalau pakai proxy /api
      # args:
      #   - VITE_API_URL=""
    container_name: lapor_frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - server

  # 2) Backend Node (Express)
  server:
    build: ./server
    container_name: lapor_backend
    env_file:
      - ./server/.env
    ports:
      - "8000:8000"   # optional: exposed ke host untuk debugging
    restart: unless-stopped
    depends_on:
      - yolo_server

  # 3) YOLO (Flask)
  yolo_server:
    build: ./yolo_server
    container_name: lapor_yolo_server
    env_file:
      - ./yolo_server/.env
    ports:
      - "5000:5000"   # optional: exposed ke host untuk debugging
    restart: unless-stopped
